# - definition for rabbitmq
# - use official rabbitmq image [https://registry.hub.docker.com/_/rabbitmq/]
rabbitmq:
  image: rabbitmq
  expose:
    - "15672"

# - definition for redis
# - use official redis image [https://registry.hub.docker.com/_/redis/]
redis:
  image: redis
  expose:
    - "6379"

# - definition for kafka
# - use spotify kafka image [https://registry.hub.docker.com/u/spotify/kafka/]
kafka:
  image: spotify/kafka
  expose:
    - "9092"
    - "2181"
  environment:
    - ADVERTISED_PORT=9092
    - ADVERTISED_HOST=`boot2docker ip`
