# - definition for rabbitmq
# - use official rabbitmq image [https://registry.hub.docker.com/_/rabbitmq/]
rabbitmq:
  image: rabbitmq
  ports:
    - "15672:15672"
    - "5672:5672"

# - definition for redis
# - use official redis image [https://registry.hub.docker.com/_/redis/]
redis:
  image: redis
  ports:
    - "6379:6379"

# - definition for kafka
# - use spotify kafka image [https://registry.hub.docker.com/u/spotify/kafka/]
kafka:
  image: spotify/kafka
  ports:
    - "9092:9092"
    - "2181:2181"
  environment:
    - ADVERTISED_PORT=9092
    - ADVERTISED_HOST=192.168.59.103

# - definition for cse play! app
cse:
  command: universal/stage/bin/stack -Dlogger.file=/conf/logger.xml
  build: .
  volumes:
    - target/:/code
  ports:
    - "9000:9000"
  links:
    - rabbitmq
    - redis
    - kafka
